/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIdRouteImport } from './routes/case-studies.$id'

const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIdRoute = CaseStudiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/case-studies/$id': typeof CaseStudiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/case-studies/$id': typeof CaseStudiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/case-studies/$id': typeof CaseStudiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/case-studies' | '/case-studies/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case-studies' | '/case-studies/$id'
  id: '__root__' | '/' | '/case-studies' | '/case-studies/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$id': {
      id: '/case-studies/$id'
      path: '/$id'
      fullPath: '/case-studies/$id'
      preLoaderRoute: typeof CaseStudiesIdRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesIdRoute: typeof CaseStudiesIdRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesIdRoute: CaseStudiesIdRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
