/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesResearchRouteImport } from './routes/case-studies.research'
import { Route as CaseStudiesDesignRouteImport } from './routes/case-studies.design'
import { Route as CaseStudies06RouteImport } from './routes/case-studies.06'
import { Route as CaseStudies05RouteImport } from './routes/case-studies.05'
import { Route as CaseStudies04RouteImport } from './routes/case-studies.04'
import { Route as CaseStudies03RouteImport } from './routes/case-studies.03'
import { Route as CaseStudies02RouteImport } from './routes/case-studies.02'
import { Route as CaseStudies01RouteImport } from './routes/case-studies.01'
import { Route as CaseStudiesDesignIndexRouteImport } from './routes/case-studies.design.index'
import { Route as CaseStudiesDesign03SlugToConfirmRouteImport } from './routes/case-studies.design.03-slug-to-confirm'
import { Route as CaseStudiesDesign02BitcoinOnBaseRouteImport } from './routes/case-studies.design.02-bitcoin-on-base'
import { Route as CaseStudiesDesign01TbtcBridgeRouteImport } from './routes/case-studies.design.01-tbtc-bridge'

const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesResearchRoute = CaseStudiesResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesDesignRoute = CaseStudiesDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudies06Route = CaseStudies06RouteImport.update({
  id: '/06',
  path: '/06',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudies05Route = CaseStudies05RouteImport.update({
  id: '/05',
  path: '/05',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudies04Route = CaseStudies04RouteImport.update({
  id: '/04',
  path: '/04',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudies03Route = CaseStudies03RouteImport.update({
  id: '/03',
  path: '/03',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudies02Route = CaseStudies02RouteImport.update({
  id: '/02',
  path: '/02',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudies01Route = CaseStudies01RouteImport.update({
  id: '/01',
  path: '/01',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesDesignIndexRoute = CaseStudiesDesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesDesignRoute,
} as any)
const CaseStudiesDesign03SlugToConfirmRoute =
  CaseStudiesDesign03SlugToConfirmRouteImport.update({
    id: '/03-slug-to-confirm',
    path: '/03-slug-to-confirm',
    getParentRoute: () => CaseStudiesDesignRoute,
  } as any)
const CaseStudiesDesign02BitcoinOnBaseRoute =
  CaseStudiesDesign02BitcoinOnBaseRouteImport.update({
    id: '/02-bitcoin-on-base',
    path: '/02-bitcoin-on-base',
    getParentRoute: () => CaseStudiesDesignRoute,
  } as any)
const CaseStudiesDesign01TbtcBridgeRoute =
  CaseStudiesDesign01TbtcBridgeRouteImport.update({
    id: '/01-tbtc-bridge',
    path: '/01-tbtc-bridge',
    getParentRoute: () => CaseStudiesDesignRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/case-studies/01': typeof CaseStudies01Route
  '/case-studies/02': typeof CaseStudies02Route
  '/case-studies/03': typeof CaseStudies03Route
  '/case-studies/04': typeof CaseStudies04Route
  '/case-studies/05': typeof CaseStudies05Route
  '/case-studies/06': typeof CaseStudies06Route
  '/case-studies/design': typeof CaseStudiesDesignRouteWithChildren
  '/case-studies/research': typeof CaseStudiesResearchRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/case-studies/design/01-tbtc-bridge': typeof CaseStudiesDesign01TbtcBridgeRoute
  '/case-studies/design/02-bitcoin-on-base': typeof CaseStudiesDesign02BitcoinOnBaseRoute
  '/case-studies/design/03-slug-to-confirm': typeof CaseStudiesDesign03SlugToConfirmRoute
  '/case-studies/design/': typeof CaseStudiesDesignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies/01': typeof CaseStudies01Route
  '/case-studies/02': typeof CaseStudies02Route
  '/case-studies/03': typeof CaseStudies03Route
  '/case-studies/04': typeof CaseStudies04Route
  '/case-studies/05': typeof CaseStudies05Route
  '/case-studies/06': typeof CaseStudies06Route
  '/case-studies/research': typeof CaseStudiesResearchRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/case-studies/design/01-tbtc-bridge': typeof CaseStudiesDesign01TbtcBridgeRoute
  '/case-studies/design/02-bitcoin-on-base': typeof CaseStudiesDesign02BitcoinOnBaseRoute
  '/case-studies/design/03-slug-to-confirm': typeof CaseStudiesDesign03SlugToConfirmRoute
  '/case-studies/design': typeof CaseStudiesDesignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/case-studies/01': typeof CaseStudies01Route
  '/case-studies/02': typeof CaseStudies02Route
  '/case-studies/03': typeof CaseStudies03Route
  '/case-studies/04': typeof CaseStudies04Route
  '/case-studies/05': typeof CaseStudies05Route
  '/case-studies/06': typeof CaseStudies06Route
  '/case-studies/design': typeof CaseStudiesDesignRouteWithChildren
  '/case-studies/research': typeof CaseStudiesResearchRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/case-studies/design/01-tbtc-bridge': typeof CaseStudiesDesign01TbtcBridgeRoute
  '/case-studies/design/02-bitcoin-on-base': typeof CaseStudiesDesign02BitcoinOnBaseRoute
  '/case-studies/design/03-slug-to-confirm': typeof CaseStudiesDesign03SlugToConfirmRoute
  '/case-studies/design/': typeof CaseStudiesDesignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/case-studies/01'
    | '/case-studies/02'
    | '/case-studies/03'
    | '/case-studies/04'
    | '/case-studies/05'
    | '/case-studies/06'
    | '/case-studies/design'
    | '/case-studies/research'
    | '/case-studies/'
    | '/case-studies/design/01-tbtc-bridge'
    | '/case-studies/design/02-bitcoin-on-base'
    | '/case-studies/design/03-slug-to-confirm'
    | '/case-studies/design/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies/01'
    | '/case-studies/02'
    | '/case-studies/03'
    | '/case-studies/04'
    | '/case-studies/05'
    | '/case-studies/06'
    | '/case-studies/research'
    | '/case-studies'
    | '/case-studies/design/01-tbtc-bridge'
    | '/case-studies/design/02-bitcoin-on-base'
    | '/case-studies/design/03-slug-to-confirm'
    | '/case-studies/design'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/case-studies/01'
    | '/case-studies/02'
    | '/case-studies/03'
    | '/case-studies/04'
    | '/case-studies/05'
    | '/case-studies/06'
    | '/case-studies/design'
    | '/case-studies/research'
    | '/case-studies/'
    | '/case-studies/design/01-tbtc-bridge'
    | '/case-studies/design/02-bitcoin-on-base'
    | '/case-studies/design/03-slug-to-confirm'
    | '/case-studies/design/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/research': {
      id: '/case-studies/research'
      path: '/research'
      fullPath: '/case-studies/research'
      preLoaderRoute: typeof CaseStudiesResearchRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/design': {
      id: '/case-studies/design'
      path: '/design'
      fullPath: '/case-studies/design'
      preLoaderRoute: typeof CaseStudiesDesignRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/06': {
      id: '/case-studies/06'
      path: '/06'
      fullPath: '/case-studies/06'
      preLoaderRoute: typeof CaseStudies06RouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/05': {
      id: '/case-studies/05'
      path: '/05'
      fullPath: '/case-studies/05'
      preLoaderRoute: typeof CaseStudies05RouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/04': {
      id: '/case-studies/04'
      path: '/04'
      fullPath: '/case-studies/04'
      preLoaderRoute: typeof CaseStudies04RouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/03': {
      id: '/case-studies/03'
      path: '/03'
      fullPath: '/case-studies/03'
      preLoaderRoute: typeof CaseStudies03RouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/02': {
      id: '/case-studies/02'
      path: '/02'
      fullPath: '/case-studies/02'
      preLoaderRoute: typeof CaseStudies02RouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/01': {
      id: '/case-studies/01'
      path: '/01'
      fullPath: '/case-studies/01'
      preLoaderRoute: typeof CaseStudies01RouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/design/': {
      id: '/case-studies/design/'
      path: '/'
      fullPath: '/case-studies/design/'
      preLoaderRoute: typeof CaseStudiesDesignIndexRouteImport
      parentRoute: typeof CaseStudiesDesignRoute
    }
    '/case-studies/design/03-slug-to-confirm': {
      id: '/case-studies/design/03-slug-to-confirm'
      path: '/03-slug-to-confirm'
      fullPath: '/case-studies/design/03-slug-to-confirm'
      preLoaderRoute: typeof CaseStudiesDesign03SlugToConfirmRouteImport
      parentRoute: typeof CaseStudiesDesignRoute
    }
    '/case-studies/design/02-bitcoin-on-base': {
      id: '/case-studies/design/02-bitcoin-on-base'
      path: '/02-bitcoin-on-base'
      fullPath: '/case-studies/design/02-bitcoin-on-base'
      preLoaderRoute: typeof CaseStudiesDesign02BitcoinOnBaseRouteImport
      parentRoute: typeof CaseStudiesDesignRoute
    }
    '/case-studies/design/01-tbtc-bridge': {
      id: '/case-studies/design/01-tbtc-bridge'
      path: '/01-tbtc-bridge'
      fullPath: '/case-studies/design/01-tbtc-bridge'
      preLoaderRoute: typeof CaseStudiesDesign01TbtcBridgeRouteImport
      parentRoute: typeof CaseStudiesDesignRoute
    }
  }
}

interface CaseStudiesDesignRouteChildren {
  CaseStudiesDesign01TbtcBridgeRoute: typeof CaseStudiesDesign01TbtcBridgeRoute
  CaseStudiesDesign02BitcoinOnBaseRoute: typeof CaseStudiesDesign02BitcoinOnBaseRoute
  CaseStudiesDesign03SlugToConfirmRoute: typeof CaseStudiesDesign03SlugToConfirmRoute
  CaseStudiesDesignIndexRoute: typeof CaseStudiesDesignIndexRoute
}

const CaseStudiesDesignRouteChildren: CaseStudiesDesignRouteChildren = {
  CaseStudiesDesign01TbtcBridgeRoute: CaseStudiesDesign01TbtcBridgeRoute,
  CaseStudiesDesign02BitcoinOnBaseRoute: CaseStudiesDesign02BitcoinOnBaseRoute,
  CaseStudiesDesign03SlugToConfirmRoute: CaseStudiesDesign03SlugToConfirmRoute,
  CaseStudiesDesignIndexRoute: CaseStudiesDesignIndexRoute,
}

const CaseStudiesDesignRouteWithChildren =
  CaseStudiesDesignRoute._addFileChildren(CaseStudiesDesignRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudies01Route: typeof CaseStudies01Route
  CaseStudies02Route: typeof CaseStudies02Route
  CaseStudies03Route: typeof CaseStudies03Route
  CaseStudies04Route: typeof CaseStudies04Route
  CaseStudies05Route: typeof CaseStudies05Route
  CaseStudies06Route: typeof CaseStudies06Route
  CaseStudiesDesignRoute: typeof CaseStudiesDesignRouteWithChildren
  CaseStudiesResearchRoute: typeof CaseStudiesResearchRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudies01Route: CaseStudies01Route,
  CaseStudies02Route: CaseStudies02Route,
  CaseStudies03Route: CaseStudies03Route,
  CaseStudies04Route: CaseStudies04Route,
  CaseStudies05Route: CaseStudies05Route,
  CaseStudies06Route: CaseStudies06Route,
  CaseStudiesDesignRoute: CaseStudiesDesignRouteWithChildren,
  CaseStudiesResearchRoute: CaseStudiesResearchRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
